"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-08 16:28:09.118978+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_clusters',
    sa.Column('cluster_key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=True),
    sa.Column('origin_document_id', sa.String(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['origin_document_id'], ['source_documents.id'], name='fk_cluster_origin_document', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_clusters')),
    sa.UniqueConstraint('cluster_key', name=op.f('uq_evidence_clusters_cluster_key'))
    )
    op.create_table('industries',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['industries.id'], name=op.f('fk_industries_parent_id_industries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industries')),
    sa.UniqueConstraint('key', name=op.f('uq_industries_key'))
    )
    op.create_table('scores',
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unavailable_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weight_coverage', sa.Float(), nullable=False),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value >= 0 AND value <= 100', name=op.f('ck_scores_value_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores')),
    sa.UniqueConstraint('subject_type', 'subject_id', 'model_name', 'model_version', 'computed_at', name='uq_score_snapshot')
    )
    op.create_index('ix_scores_subject', 'scores', ['subject_type', 'subject_id'], unique=False)
    op.create_table('signals',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('subject_key', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals')),
    sa.UniqueConstraint('key', name=op.f('uq_signals_key'))
    )
    op.create_index('ix_signals_subject_key', 'signals', ['subject_key'], unique=False)
    op.create_table('sources',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('publisher', sa.String(length=256), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_class', sa.Text(), nullable=False),
    sa.Column('base_quality', sa.Integer(), nullable=False),
    sa.Column('homepage_url', sa.String(length=512), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(is_synthetic = false) OR (data_mode = 'DEMO')", name=op.f('ck_sources_synthetic_sources_are_demo')),
    sa.CheckConstraint('base_quality >= 0 AND base_quality <= 100', name=op.f('ck_sources_quality_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('key', name=op.f('uq_sources_key'))
    )
    op.create_index('ix_sources_source_class', 'sources', ['source_class'], unique=False)
    op.create_table('themes',
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('anchor_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('maturity', sa.Text(), nullable=False),
    sa.Column('market_awareness', sa.Text(), nullable=False),
    sa.Column('market_awareness_mode', sa.Text(), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_themes')),
    sa.UniqueConstraint('slug', name=op.f('uq_themes_slug'))
    )
    op.create_index('ix_themes_last_updated_at', 'themes', ['last_updated_at'], unique=False)
    op.create_index('ix_themes_maturity', 'themes', ['maturity'], unique=False)
    op.create_table('companies',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('cik', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('industry_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_fictional', sa.Boolean(), nullable=False),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('provenance_note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(is_fictional = false AND data_mode <> 'DEMO') OR (is_fictional = true AND data_mode = 'DEMO')", name=op.f('ck_companies_demo_companies_are_fictional')),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_companies_industry_id_industries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('key', name=op.f('uq_companies_key'))
    )
    op.create_index('ix_companies_industry_id', 'companies', ['industry_id'], unique=False)
    op.create_index('ix_companies_ticker', 'companies', ['ticker'], unique=False)
    op.create_table('events',
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_key', sa.String(length=128), nullable=False),
    sa.Column('entity_label', sa.String(length=256), nullable=False),
    sa.Column('subject_key', sa.String(length=128), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=True),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=256), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_events_confidence_range')),
    sa.CheckConstraint('magnitude >= 0 AND magnitude <= 1', name=op.f('ck_events_magnitude_range')),
    sa.ForeignKeyConstraint(['cluster_id'], ['evidence_clusters.id'], name=op.f('fk_events_cluster_id_evidence_clusters')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_events_dedupe_key'))
    )
    op.create_index('ix_events_entity', 'events', ['entity_type', 'entity_key'], unique=False)
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('ix_events_occurred_at', 'events', ['occurred_at'], unique=False)
    op.create_index('ix_events_subject_key', 'events', ['subject_key'], unique=False)
    op.create_table('hypotheses',
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk_hypotheses_theme_id_themes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hypotheses'))
    )
    op.create_index('ix_hypotheses_theme_id', 'hypotheses', ['theme_id'], unique=False)
    op.create_table('score_components',
    sa.Column('score_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('raw_input', sa.Float(), nullable=True),
    sa.Column('normalized', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('effective_weight', sa.Float(), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], name=op.f('fk_score_components_score_id_scores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_components')),
    sa.UniqueConstraint('score_id', 'key', name='uq_score_component')
    )
    op.create_index('ix_score_components_score_id', 'score_components', ['score_id'], unique=False)
    op.create_table('signal_observations',
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bucket_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('net_direction', sa.Text(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('independent_source_count', sa.Integer(), nullable=False),
    sa.Column('underlying_event_count', sa.Integer(), nullable=False),
    sa.Column('source_diversity', sa.Float(), nullable=False),
    sa.Column('primary_source_ratio', sa.Float(), nullable=False),
    sa.Column('avg_source_quality', sa.Float(), nullable=False),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computation_version', sa.String(length=32), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('strength >= 0 AND strength <= 100', name=op.f('ck_signal_observations_strength_range')),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_signal_observations_signal_id_signals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_observations')),
    sa.UniqueConstraint('signal_id', 'bucket_start', 'computation_version', name='uq_signal_bucket')
    )
    op.create_index('ix_signal_obs_bucket_start', 'signal_observations', ['bucket_start'], unique=False)
    op.create_table('source_documents',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_at_inferred', sa.Boolean(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('provider_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('origin_ref', sa.String(length=256), nullable=True),
    sa.Column('cluster_id', sa.String(), nullable=True),
    sa.Column('cluster_method', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_mode <> 'DEMO' OR url LIKE '%%.invalid/%%' OR url LIKE '%%.invalid'", name=op.f('ck_source_documents_demo_documents_use_invalid_domain')),
    sa.ForeignKeyConstraint(['cluster_id'], ['evidence_clusters.id'], name=op.f('fk_source_documents_cluster_id_evidence_clusters')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_documents_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents')),
    sa.UniqueConstraint('source_id', 'content_hash', name='uq_document_source_content')
    )
    op.create_index('ix_source_documents_cluster_id', 'source_documents', ['cluster_id'], unique=False)
    op.create_index('ix_source_documents_content_hash', 'source_documents', ['content_hash'], unique=False)
    op.create_index('ix_source_documents_data_mode', 'source_documents', ['data_mode'], unique=False)
    op.create_index('ix_source_documents_event_at', 'source_documents', ['event_at'], unique=False)
    op.create_index('ix_source_documents_published_at', 'source_documents', ['published_at'], unique=False)
    op.create_table('theme_signals',
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_theme_signals_signal_id_signals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk_theme_signals_theme_id_themes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('theme_id', 'signal_id', name=op.f('pk_theme_signals'))
    )
    op.create_table('trends',
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('theme_id', sa.String(), nullable=True),
    sa.Column('observation_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('baseline_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('baseline_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_strength', sa.Float(), nullable=False),
    sa.Column('baseline_strength', sa.Float(), nullable=False),
    sa.Column('acceleration', sa.Float(), nullable=False),
    sa.Column('frequency_change', sa.Float(), nullable=False),
    sa.Column('independence_change', sa.Float(), nullable=False),
    sa.Column('novelty', sa.Float(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computation_version', sa.String(length=32), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('acceleration >= -100 AND acceleration <= 100', name=op.f('ck_trends_acceleration_range')),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_trends_signal_id_signals')),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk_trends_theme_id_themes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trends')),
    sa.UniqueConstraint('signal_id', 'observation_end', 'computation_version', name='uq_trend_window')
    )
    op.create_index('ix_trends_theme_id', 'trends', ['theme_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('excerpt_start', sa.Integer(), nullable=False),
    sa.Column('excerpt_end', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('entity_hint', sa.String(length=256), nullable=True),
    sa.Column('subject_key', sa.String(length=128), nullable=True),
    sa.Column('extracted_by', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_evidence_items_confidence_range')),
    sa.ForeignKeyConstraint(['cluster_id'], ['evidence_clusters.id'], name=op.f('fk_evidence_items_cluster_id_evidence_clusters')),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_evidence_items_document_id_source_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items')),
    sa.UniqueConstraint('document_id', 'excerpt_start', 'rule_key', 'extractor_version', name='uq_evidence_span')
    )
    op.create_index('ix_evidence_items_cluster_id', 'evidence_items', ['cluster_id'], unique=False)
    op.create_index('ix_evidence_items_event_at', 'evidence_items', ['event_at'], unique=False)
    op.create_index('ix_evidence_items_event_type', 'evidence_items', ['event_type'], unique=False)
    op.create_index('ix_evidence_items_subject_key', 'evidence_items', ['subject_key'], unique=False)
    op.create_table('research_runs',
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consumed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], name=op.f('fk_research_runs_hypothesis_id_hypotheses')),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk_research_runs_theme_id_themes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_runs'))
    )
    op.create_index('ix_research_runs_theme_id', 'research_runs', ['theme_id'], unique=False)
    op.create_table('securities',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('security_type', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_securities_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_securities')),
    sa.UniqueConstraint('ticker', 'exchange', name='uq_security_listing')
    )
    op.create_table('theme_company_exposures',
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('order_of_effect', sa.Integer(), nullable=False),
    sa.Column('exposure_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computation_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('exposure_score >= 0 AND exposure_score <= 100', name=op.f('ck_theme_company_exposures_exposure_range')),
    sa.CheckConstraint('order_of_effect >= 1 AND order_of_effect <= 5', name=op.f('ck_theme_company_exposures_order_range')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_theme_company_exposures_company_id_companies')),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk_theme_company_exposures_theme_id_themes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_theme_company_exposures')),
    sa.UniqueConstraint('theme_id', 'company_id', 'computation_version', name='uq_theme_company_exposure')
    )
    op.create_index('ix_exposures_theme_id', 'theme_company_exposures', ['theme_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.String(length=32), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consumed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], name=op.f('fk_agent_runs_research_run_id_research_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index('ix_agent_runs_research_run_id', 'agent_runs', ['research_run_id'], unique=False)
    op.create_index('ix_agent_runs_started_at', 'agent_runs', ['started_at'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('source_entity_type', sa.Text(), nullable=False),
    sa.Column('source_entity_key', sa.String(length=128), nullable=False),
    sa.Column('target_entity_type', sa.Text(), nullable=False),
    sa.Column('target_entity_key', sa.String(length=128), nullable=False),
    sa.Column('relationship_type', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_entity_relationships_confidence_range')),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name=op.f('ck_entity_relationships_weight_range')),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.id'], name=op.f('fk_entity_relationships_evidence_id_evidence_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_relationships')),
    sa.UniqueConstraint('source_entity_type', 'source_entity_key', 'target_entity_type', 'target_entity_key', 'relationship_type', name='uq_relationship_edge')
    )
    op.create_index('ix_entity_rel_source', 'entity_relationships', ['source_entity_type', 'source_entity_key'], unique=False)
    op.create_index('ix_entity_rel_target', 'entity_relationships', ['target_entity_type', 'target_entity_key'], unique=False)
    op.create_table('event_evidence',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_evidence_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.id'], name=op.f('fk_event_evidence_evidence_id_evidence_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'evidence_id', name=op.f('pk_event_evidence'))
    )
    op.create_table('research_reports',
    sa.Column('research_run_id', sa.String(), nullable=False),
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generator', sa.String(length=64), nullable=False),
    sa.Column('generator_version', sa.String(length=32), nullable=False),
    sa.Column('opportunity_score_id', sa.String(), nullable=True),
    sa.Column('confidence_score_id', sa.String(), nullable=True),
    sa.Column('trend_score_id', sa.String(), nullable=True),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confidence_score_id'], ['scores.id'], name=op.f('fk_research_reports_confidence_score_id_scores')),
    sa.ForeignKeyConstraint(['opportunity_score_id'], ['scores.id'], name=op.f('fk_research_reports_opportunity_score_id_scores')),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], name=op.f('fk_research_reports_research_run_id_research_runs')),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], name=op.f('fk_research_reports_theme_id_themes')),
    sa.ForeignKeyConstraint(['trend_score_id'], ['scores.id'], name=op.f('fk_research_reports_trend_score_id_scores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_reports')),
    sa.UniqueConstraint('research_run_id', name='uq_report_per_run')
    )
    op.create_index('ix_reports_theme_id', 'research_reports', ['theme_id'], unique=False)
    op.create_table('research_plans',
    sa.Column('research_run_id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=True),
    sa.Column('hypothesis_statement', sa.Text(), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('planner_version', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_research_plans_agent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], name=op.f('fk_research_plans_research_run_id_research_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_plans'))
    )
    op.create_table('research_questions',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('seeks_counter_evidence', sa.Boolean(), nullable=False),
    sa.Column('search_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name=op.f('ck_research_questions_priority_range')),
    sa.ForeignKeyConstraint(['plan_id'], ['research_plans.id'], name=op.f('fk_research_questions_plan_id_research_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_questions'))
    )
    op.create_index('ix_research_questions_plan_id', 'research_questions', ['plan_id'], unique=False)
    op.create_table('research_findings',
    sa.Column('research_run_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.Text(), nullable=False),
    sa.Column('stance', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('independent_source_count', sa.Integer(), nullable=False),
    sa.Column('source_diversity', sa.Float(), nullable=False),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('data_mode', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_research_findings_confidence_range')),
    sa.ForeignKeyConstraint(['question_id'], ['research_questions.id'], name=op.f('fk_research_findings_question_id_research_questions')),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], name=op.f('fk_research_findings_research_run_id_research_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_findings'))
    )
    op.create_index('ix_findings_research_run_id', 'research_findings', ['research_run_id'], unique=False)
    op.create_index('ix_findings_stance', 'research_findings', ['stance'], unique=False)
    op.create_table('search_runs',
    sa.Column('research_run_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=True),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('provider_mode', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('new_document_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['research_questions.id'], name=op.f('fk_search_runs_question_id_research_questions')),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], name=op.f('fk_search_runs_research_run_id_research_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_runs'))
    )
    op.create_index('ix_search_runs_research_run_id', 'search_runs', ['research_run_id'], unique=False)
    op.create_table('finding_evidence',
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_items.id'], name=op.f('fk_finding_evidence_evidence_id_evidence_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['research_findings.id'], name=op.f('fk_finding_evidence_finding_id_research_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'evidence_id', name=op.f('pk_finding_evidence'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finding_evidence')
    op.drop_index('ix_search_runs_research_run_id', table_name='search_runs')
    op.drop_table('search_runs')
    op.drop_index('ix_findings_stance', table_name='research_findings')
    op.drop_index('ix_findings_research_run_id', table_name='research_findings')
    op.drop_table('research_findings')
    op.drop_index('ix_research_questions_plan_id', table_name='research_questions')
    op.drop_table('research_questions')
    op.drop_table('research_plans')
    op.drop_index('ix_reports_theme_id', table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_table('event_evidence')
    op.drop_index('ix_entity_rel_target', table_name='entity_relationships')
    op.drop_index('ix_entity_rel_source', table_name='entity_relationships')
    op.drop_table('entity_relationships')
    op.drop_index('ix_agent_runs_started_at', table_name='agent_runs')
    op.drop_index('ix_agent_runs_research_run_id', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_exposures_theme_id', table_name='theme_company_exposures')
    op.drop_table('theme_company_exposures')
    op.drop_table('securities')
    op.drop_index('ix_research_runs_theme_id', table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index('ix_evidence_items_subject_key', table_name='evidence_items')
    op.drop_index('ix_evidence_items_event_type', table_name='evidence_items')
    op.drop_index('ix_evidence_items_event_at', table_name='evidence_items')
    op.drop_index('ix_evidence_items_cluster_id', table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index('ix_trends_theme_id', table_name='trends')
    op.drop_table('trends')
    op.drop_table('theme_signals')
    op.drop_index('ix_source_documents_published_at', table_name='source_documents')
    op.drop_index('ix_source_documents_event_at', table_name='source_documents')
    op.drop_index('ix_source_documents_data_mode', table_name='source_documents')
    op.drop_index('ix_source_documents_content_hash', table_name='source_documents')
    op.drop_index('ix_source_documents_cluster_id', table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index('ix_signal_obs_bucket_start', table_name='signal_observations')
    op.drop_table('signal_observations')
    op.drop_index('ix_score_components_score_id', table_name='score_components')
    op.drop_table('score_components')
    op.drop_index('ix_hypotheses_theme_id', table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index('ix_events_subject_key', table_name='events')
    op.drop_index('ix_events_occurred_at', table_name='events')
    op.drop_index('ix_events_event_type', table_name='events')
    op.drop_index('ix_events_entity', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_companies_ticker', table_name='companies')
    op.drop_index('ix_companies_industry_id', table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_themes_maturity', table_name='themes')
    op.drop_index('ix_themes_last_updated_at', table_name='themes')
    op.drop_table('themes')
    op.drop_index('ix_sources_source_class', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_signals_subject_key', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_scores_subject', table_name='scores')
    op.drop_table('scores')
    op.drop_table('industries')
    op.drop_table('evidence_clusters')
    # ### end Alembic commands ###
