"""add event knowable_at for temporal integrity

Revision ID: 0002_knowable_at
Revises: 0001_initial
Create Date: 2026-09-08 18:54:17.222137+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '0002_knowable_at'
down_revision: str | None = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Added nullable first, then backfilled, then constrained: adding a NOT NULL column
    # outright fails on any table that already holds rows.
    op.add_column("events", sa.Column("knowable_at", sa.DateTime(timezone=True), nullable=True))

    # An event became knowable when the FIRST document supporting it was published.
    op.execute(
        """
        UPDATE events e
        SET knowable_at = sub.first_published
        FROM (
            SELECT ee.event_id, MIN(ei.published_at) AS first_published
            FROM event_evidence ee
            JOIN evidence_items ei ON ei.id = ee.evidence_id
            GROUP BY ee.event_id
        ) sub
        WHERE sub.event_id = e.id
        """
    )
    # Defensive: an event with no surviving evidence should not exist, but must not block
    # the migration. Falling back to occurred_at is the conservative choice — it can only
    # make an event look knowable EARLIER, never later, so it cannot mask contamination.
    op.execute("UPDATE events SET knowable_at = occurred_at WHERE knowable_at IS NULL")

    op.alter_column("events", "knowable_at", nullable=False)
    op.create_index("ix_events_knowable_at", "events", ["knowable_at"], unique=False)

    # This FK belongs to the original schema but was omitted by autogenerate in 0001
    # because of its use_alter cycle; adding it here where it was detected.
    op.create_foreign_key(
        "fk_cluster_origin_document",
        "evidence_clusters",
        "source_documents",
        ["origin_document_id"],
        ["id"],
        use_alter=True,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cluster_origin_document', 'evidence_clusters', type_='foreignkey')
    op.drop_index('ix_events_knowable_at', table_name='events')
    op.drop_column('events', 'knowable_at')
    # ### end Alembic commands ###
